#!/bin/bash
# Auto-generated by Claude to install deps and start dev server
set -e

cd "/Users/yingcong/Downloads/seedance_metamind/drama_metamind_fontend/web"

echo "==> 当前目录: $(pwd)"
echo "==> Node 版本: $(node -v)"
echo "==> npm 版本: $(npm -v)"
echo ""

echo "==> 清理旧的 node_modules 和 lock 文件..."
rm -rf node_modules package-lock.json

echo ""
echo "==> 开始 npm install (大概 1-2 分钟)..."
npm install --no-audit --no-fund

echo ""
echo "==> 安装完成,启动 dev server..."
echo "==> 启动后在浏览器打开 http://localhost:5173"
echo ""

npm run dev
